const BUY_BUTTERSCOTCH ="BUY_BUTTERSCOTCH"
const BUY_BROWNIE="BUY_BROWNIE"
const BUY_PINEAPPLE="BUY_PINEAPPLE"
const BUY_STRAWBERRY="BUY_STRAWBERRY"

export default {BUY_BUTTERSCOTCH,BUY_BROWNIE,BUY_PINEAPPLE,BUY_STRAWBERRY}